max_rows_per_report: 500
hide_rows_automatically: true
rules:
  - name: "Potential Vulnerabilities"
    enabled: true
    matchers:
      - "[&|\\?](doc|pdf|pdfDoc|document|file|path|download|image|img|file_path|filePath|docPath|upload|uploadPath)=([^&]+)"
    extractors:
      - name: "SSRF / Path Traversal"
        group: 1
        expression: "[&|\\?]((doc|pdf|pdfDoc|document|file|path|download|image|img|file_path|filePath|docPath|upload|uploadPath)=([^&]+))"
  - name: "Credentials"
    enabled: true
    matchers:
      - "[\\?|&](passw|pwd|password|passwd|username|user|usr|login|loginid)=[^&]"
      - "[\\?|&](email|mail)=([^&]+[@|%40]{1}[^&]+\\.[^&]+)"
      - "[\\?|&](jwt|apiKey|api|key|token|access_token|refresh_token)=(eyJhbGciOiJ){1}[a-z0-9\\-_\\+/=%]+\\.(eyJ){1}[a-z0-9\\-_\\+/=%]+\\.[a-z0-9\\-_\\+/=%]+"
      - "[\\?|&](phpsessid|jsessionid|asp\\.net_sessionid|_session_id|sessionid|connect\\.sid|laravel_session|cfid)=[^&]+"
    extractors:
      - name: "Password"
        group: 2
        expression: "(passw|pwd|password|passwd)=([^&]+)"
      - name: "User"
        group: 2
        expression: "(username|user|usr|login|loginid)=([^&]+)"
      - name: "Email"
        group: 2
        expression: "(email|mail)=([^&]+[@|%40]{1}[^&]+\\.[^&]+)"
      - name: "JWT Token"
        group: 2
        expression: "(jwt|apiKey|api|key|token|access_token|refresh_token)=((eyJhbGciOiJ){1}[a-z0-9\\-_\\+/=%]+\\.(eyJ){1}[a-z0-9\\-_\\+/=%]+\\.[a-z0-9\\-_\\+/=%]+)"
      - name: "Sessions"
        group: 2
        expression: "(phpsessid|jsessionid|asp\\.net_sessionid|_session_id|sessionid|connect\\.sid|laravel_session|cfid)=([^&]+)"
  - name: "Files"
    enabled: true
    matchers:
      # ([\\?&](.+=.+)*)*$
      - "/((access_log|error_log|l0g|log|logs|access|accesses|credentials|sessions|session|user|users|email)(\\.txt|\\.log))([\\?&](.+=.+)*)*$"
      - "/(web\\.config|phpinfo\\.php|\\.htaccess|\\.git|\\.git\\-ignore)([\\?&](.+=.+)*)*$"
      - "([^/=]+\\.(zip|rar|7z|tar\\.gz))([\\?&](.+=.+)*)*$"
    extractors:
      - name: "Logs"
        group: 1
        expression: "((access_log|error_log|l0g|log|logs)(\\.txt|\\.log|\\.zip))([\\?&](.+=.+)*)*$"
      - name: "Authentication"
        group: 1
        expression: "((access|accesses|credentials|sessions|session|user|users|email)(\\.txt|\\.log))([\\?&](.+=.+)*)*$"
      - name: "Configurations"
        group: 1
        expression: "/(web\\.config|phpinfo\\.php|\\.htaccess)([\\?&](.+=.+)*)*$"
      - name: "Archives"
        group: 1
        expression: "([^/=]+\\.(zip|rar|7z|tar\\.gz))([\\?&](.+=.+)*)*$"
      - name: "Git"
        group: 1
        expression: "/(\\.git|\\.git\\-ignore)([\\?&](.+=.+)*)*$"
  - name: "APIs"
    enabled: true
    matchers:
        - "/([^\\?|&|/]\\.wadl)"
        - "/((swagger|swagger-ui)\\.(html|yaml|json|js))"
    extractors:
      - name: "WADL Files"
        group: 1
        expression: "/([^\\?|&|/]\\.wadl)"
      - name: "Swagger"
        group: 1
        expression: "/((swagger|swagger-ui)\\.(html|yaml|json|js))"